"""initial_schema

Revision ID: 13a13a72fd7a
Revises: 
Create Date: 2026-05-27 20:21:58.433382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a13a72fd7a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overall_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recommendation', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_session_overall_score'), ['overall_score'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_recommendation'), ['recommendation'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_recommendation'))
        batch_op.drop_index(batch_op.f('ix_session_overall_score'))
        batch_op.drop_column('recommendation')
        batch_op.drop_column('overall_score')

    # ### end Alembic commands ###
